-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.athlete_aliases
(
    id serial NOT NULL,
    athlete_id uuid NOT NULL,
    source_id integer NOT NULL,
    external_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    external_name character varying(255) COLLATE pg_catalog."default",
    url_slug character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT athlete_aliases_pkey PRIMARY KEY (id),
    CONSTRAINT _source_athlete_uc UNIQUE (source_id, external_id)
);

CREATE TABLE IF NOT EXISTS public.athlete_timelines
(
    id serial NOT NULL,
    athlete_id uuid,
    hs_start_year integer,
    hs_end_year integer,
    hs_graduated boolean DEFAULT false,
    college_start_year integer,
    college_end_year integer,
    college_graduated boolean DEFAULT false,
    is_transfer boolean DEFAULT false,
    covid_years integer DEFAULT 0,
    medical_redshirts integer DEFAULT 0,
    rs_xc boolean DEFAULT false,
    rs_indoor boolean DEFAULT false,
    rs_outdoor boolean DEFAULT false,
    current_level character varying(20) COLLATE pg_catalog."default",
    has_gap_year boolean DEFAULT false,
    CONSTRAINT athlete_timelines_pkey PRIMARY KEY (id),
    CONSTRAINT athlete_timelines_athlete_id_key UNIQUE (athlete_id)
);

CREATE TABLE IF NOT EXISTS public.athletes
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    display_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(1) COLLATE pg_catalog."default",
    grad_year integer,
    CONSTRAINT athletes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.facilities
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    city character varying(255) COLLATE pg_catalog."default",
    state character varying(50) COLLATE pg_catalog."default",
    latitude numeric(10, 6),
    longitude numeric(10, 6),
    CONSTRAINT facilities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.meets
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    url character varying(500) COLLATE pg_catalog."default",
    date_start date,
    date_end date,
    season character varying(50) COLLATE pg_catalog."default",
    venue_id integer,
    facility_type character varying(100) COLLATE pg_catalog."default",
    altitude numeric(8, 2) DEFAULT 0.0,
    importance_tier integer DEFAULT 1,
    CONSTRAINT meets_pkey PRIMARY KEY (id),
    CONSTRAINT meets_url_key UNIQUE (url)
);

CREATE TABLE IF NOT EXISTS public.performances
(
    id serial NOT NULL,
    race_id integer NOT NULL,
    athlete_id uuid NOT NULL,
    team_id uuid,
    mark_raw character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mark_seconds numeric(10, 3),
    mark_metric numeric(10, 3),
    overall_place integer,
    heat_place integer,
    CONSTRAINT performances_pkey PRIMARY KEY (id),
    CONSTRAINT _athlete_race_uc UNIQUE (athlete_id, race_id)
);

CREATE TABLE IF NOT EXISTS public.races
(
    id serial NOT NULL,
    meet_id integer NOT NULL,
    standard_event_id integer,
    name_raw character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(1) COLLATE pg_catalog."default",
    round character varying(50) COLLATE pg_catalog."default",
    heat_number integer DEFAULT 1,
    wind numeric(5, 2) DEFAULT 0.0,
    CONSTRAINT races_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sources
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    base_url character varying(255) COLLATE pg_catalog."default",
    trust_level integer DEFAULT 1,
    CONSTRAINT sources_pkey PRIMARY KEY (id),
    CONSTRAINT sources_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.standard_events
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    distance_meters numeric(10, 2),
    is_field boolean DEFAULT false,
    is_relay boolean DEFAULT false,
    CONSTRAINT standard_events_pkey PRIMARY KEY (id),
    CONSTRAINT standard_events_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.team_aliases
(
    id serial NOT NULL,
    team_id uuid NOT NULL,
    source_id integer NOT NULL,
    external_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    external_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT team_aliases_pkey PRIMARY KEY (id),
    CONSTRAINT _source_team_uc UNIQUE (source_id, external_id)
);

CREATE TABLE IF NOT EXISTS public.teams
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    classification character varying(50) COLLATE pg_catalog."default",
    conference character varying(100) COLLATE pg_catalog."default",
    scraped boolean DEFAULT false,
    CONSTRAINT teams_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tracks
(
    id serial NOT NULL,
    facility_id integer,
    facility_type character varying(100) COLLATE pg_catalog."default",
    altitude_meters numeric(8, 2),
    CONSTRAINT tracks_pkey PRIMARY KEY (id),
    CONSTRAINT _facility_track_uc UNIQUE (facility_id, facility_type)
);

ALTER TABLE IF EXISTS public.athlete_aliases
    ADD CONSTRAINT athlete_aliases_athlete_id_fkey FOREIGN KEY (athlete_id)
    REFERENCES public.athletes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_athlete_aliases_athlete_id
    ON public.athlete_aliases(athlete_id);


ALTER TABLE IF EXISTS public.athlete_aliases
    ADD CONSTRAINT athlete_aliases_source_id_fkey FOREIGN KEY (source_id)
    REFERENCES public.sources (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.athlete_timelines
    ADD CONSTRAINT athlete_timelines_athlete_id_fkey FOREIGN KEY (athlete_id)
    REFERENCES public.athletes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS athlete_timelines_athlete_id_key
    ON public.athlete_timelines(athlete_id);


ALTER TABLE IF EXISTS public.performances
    ADD CONSTRAINT performances_athlete_id_fkey FOREIGN KEY (athlete_id)
    REFERENCES public.athletes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_performances_athlete_id
    ON public.performances(athlete_id);


ALTER TABLE IF EXISTS public.performances
    ADD CONSTRAINT performances_race_id_fkey FOREIGN KEY (race_id)
    REFERENCES public.races (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_performances_race_id
    ON public.performances(race_id);


ALTER TABLE IF EXISTS public.performances
    ADD CONSTRAINT performances_team_id_fkey FOREIGN KEY (team_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_performances_team_id
    ON public.performances(team_id);


ALTER TABLE IF EXISTS public.races
    ADD CONSTRAINT races_meet_id_fkey FOREIGN KEY (meet_id)
    REFERENCES public.meets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_races_meet_id
    ON public.races(meet_id);


ALTER TABLE IF EXISTS public.races
    ADD CONSTRAINT races_standard_event_id_fkey FOREIGN KEY (standard_event_id)
    REFERENCES public.standard_events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_races_standard_event_id
    ON public.races(standard_event_id);


ALTER TABLE IF EXISTS public.team_aliases
    ADD CONSTRAINT team_aliases_source_id_fkey FOREIGN KEY (source_id)
    REFERENCES public.sources (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.team_aliases
    ADD CONSTRAINT team_aliases_team_id_fkey FOREIGN KEY (team_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_team_aliases_team_id
    ON public.team_aliases(team_id);


ALTER TABLE IF EXISTS public.tracks
    ADD CONSTRAINT tracks_facility_id_fkey FOREIGN KEY (facility_id)
    REFERENCES public.facilities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;